// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IconFeatherTrash: typeof import('virtual:vite-icons/feather/trash')['default']
    IconHeroiconsOutlineTrash: typeof import('virtual:vite-icons/heroicons-outline/trash')['default']
    IconHeroiconsOutlineViewGrid: typeof import('virtual:vite-icons/heroicons-outline/view-grid')['default']
    IconHeroiconsOutlineViewList: typeof import('virtual:vite-icons/heroicons-outline/view-list')['default']
  }
}

export { }
